from agent.state import IncidentState
from github import Github
import os

g = Github(os.getenv("GITHUB_TOKEN"))

def branch_and_pr(state: IncidentState) -> dict:

    incident_id = state.get("incident_id")
    changed_files = state.get("changed_files") or {}
    root_cause_summary = state.get("root_cause_summary")
    suspected_commit = state.get("suspected_commit")
    fix_plan = state.get("fix_plan", {})

    repo = g.get_repo(f"{os.getenv('GITHUB_REPO_OWNER')}/{os.getenv('GITHUB_TARGET_REPO')}")
    
    branch_name = f"fix/INC-{incident_id}-null-check"
    main_sha = repo.get_branch("main").commit.sha
    repo.create_git_ref(
        ref=f"refs/heads/{branch_name}",
        sha=main_sha
    )

    for file_path, file_content in changed_files.items():
        existing_file = repo.get_contents(file_path, ref="main")
        repo.update_file(
            path=file_path,
            message=f"fix: restore null checks - incident {incident_id}",
            content=file_content,
            sha=existing_file.sha,
            branch=branch_name
        )

    pr_body = f"""
## 🚨 Auto-generated Fix — Incident {incident_id}

**Severity:** P1  
**Service:** payment-service  
**Status:** Automated fix — awaiting human approval

## Root Cause
{root_cause_summary}

## Correlated Commit
{suspected_commit}

## Fix Applied
Restored null checks in PaymentValidator.java before calling payment.getAmount()

## Fix Plan
{fix_plan.get('immediate_mitigation', '')}

## Test Plan
{chr(10).join(fix_plan.get('test_plan', []))}

## Rollback Plan
{fix_plan.get('rollback_plan', '')}

## ⚠️ Human Approval Required
This PR was auto-generated by the DevOps Incident Response Agent.
Do NOT merge without human review and approval.
"""

    pr = repo.create_pull(
        title=f"[{incident_id}] Fix NullPointerException in PaymentValidator",
        body=pr_body,
        head=branch_name,
        base="main"
    )

    return {
        "fix_pr_url": pr.html_url,
        "branch_name": branch_name,
        "current_status": "pr_created"
    }